# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
sudo: required

language: python
python: 3.6

env:
  - TOXENV=py36

services:
  - docker

before_install:
  - sudo apt-get install ncbi-blast+ clustalo build-essential git curl
  - git clone https://github.com/nmdp-bioinformatics/imgt_biosqldb
  - cd imgt_biosqldb
  - docker build --build-arg RELEASES="3310" -t imgt_biosqldb:3310 . 
  - cd ..

before_script:
  - sleep 10

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt
  - pip install -U tox
  - pip install python-coveralls coveralls
  - docker run -d --name imgt_biosqldb -p 3307:3306 -e MYSQL_ROOT_PASSWORD=my-secret-pw imgt_biosqldb:3310
  - sleep 30

# command to run tests, e.g. python setup.py test
script: 
  - tox -e ${TOXENV}
  - coverage run --source=seqann -m unittest -v
  - coverage report -m

after_success:
  - coveralls


